import { useEffect, useRef, useState } from 'react';

const makeStyle = () => ({ topText: { color: '#2F80ED', fontSize: 72, fontFamily: 'Noto Sans TC', x: 50, y: 22 }, bottomText: { color: '#2F80ED', fontSize: 72, fontFamily: 'Noto Sans TC', x: 50, y: 52 } });
const fonts = ['Noto Sans TC', 'Arial', 'Georgia', 'Courier New'];

export default function App() {
  const [selectedFile, setSelectedFile] = useState(null), [fileId, setFileId] = useState(null), [clips, setClips] = useState([]), [status, setStatus] = useState('等待上傳'), [error, setError] = useState(''), [videoUrl, setVideoUrl] = useState(''), [clipCount, setClipCount] = useState(3), [clipDuration, setClipDuration] = useState(15), [playingClipId, setPlayingClipId] = useState(null);
  const videoRef = useRef(null);
  useEffect(() => { fetch('/api/default-video').then((r) => r.ok ? r.json() : null).then((v) => { if (v) { setFileId(v.fileId); setVideoUrl(v.videoUrl); setSelectedFile({ name: v.originalName }); setStatus('預設影片已載入，可直接開始分析'); } }).catch(() => {}); }, []);
  const analyze = async (id) => { setError(''); setStatus('正在分析語音與高光片段…'); try { const r = await fetch('/api/analyze', { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ fileId: id, clipCount, clipDuration }) }); const data = await r.json(); if (!r.ok) throw new Error(data.error || '影片分析失敗'); setClips(data.clips.map((c) => ({ ...c, top_text: c.top_text || c.title, caption: c.bottom_text || c.title, style: makeStyle(), activeLayer: 'topText' }))); setStatus(`已找到 ${data.clips.length} 個候選片段`); } catch (e) { setError(e.message); setStatus('需要處理'); } };
  async function upload(file) { setSelectedFile(file); setVideoUrl(URL.createObjectURL(file)); setClips([]); setStatus('正在上傳…'); try { const form = new FormData(); form.append('video', file); const r = await fetch('/api/upload', { method: 'POST', body: form }); const data = await r.json(); if (!r.ok) throw new Error(data.error); setFileId(data.fileId); await analyze(data.fileId); } catch (e) { setError(e.message); setStatus('需要處理'); } }
  const update = (id, field, value) => setClips((all) => all.map((c) => c.id === id ? { ...c, [field]: ['start_time', 'end_time'].includes(field) ? Number(value) : value } : c));
  const updateLayer = (id, layer, field, value) => setClips((all) => all.map((c) => c.id === id ? { ...c, style: { ...c.style, [layer]: { ...c.style[layer], [field]: ['x', 'y', 'fontSize'].includes(field) ? Number(value) : value } } } : c));
  const setLayer = (id, activeLayer) => setClips((all) => all.map((c) => c.id === id ? { ...c, activeLayer } : c));
  const resetPosition = (id, layer) => { updateLayer(id, layer, 'x', 50); updateLayer(id, layer, 'y', layer === 'topText' ? 22 : 52); };
  const position = (event, clip) => { const r = event.currentTarget.getBoundingClientRect(); const x = Math.round(Math.max(5, Math.min(95, ((event.clientX - r.left) / r.width) * 100))); const y = Math.round(Math.max(5, Math.min(95, ((event.clientY - r.top) / r.height) * 100))); updateLayer(clip.id, clip.activeLayer, 'x', x); updateLayer(clip.id, clip.activeLayer, 'y', y); };
  const stopOtherVideos = (event) => { document.querySelectorAll('video').forEach((video) => { if (video !== event.currentTarget) video.pause(); }); };
  const preview = (clip) => { const v = videoRef.current; if (!v) return; if (playingClipId === clip.id && !v.paused) { v.pause(); v.ontimeupdate = null; setPlayingClipId(null); return; } document.querySelectorAll('video').forEach((video) => video.pause()); v.ontimeupdate = null; v.currentTime = clip.start_time; v.play(); setPlayingClipId(clip.id); v.ontimeupdate = () => { if (v.currentTime >= clip.end_time) { v.pause(); v.ontimeupdate = null; setPlayingClipId(null); } }; };
  async function renderOne(clip) { update(clip.id, 'rendering', true); try { const r = await fetch('/api/render', { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ fileId, clips: [clip] }) }); const data = await r.json(); if (!r.ok) throw new Error(data.error || '影片渲染失敗'); update(clip.id, 'renderedUrl', data.outputs[0].downloadUrl); update(clip.id, 'rendering', false); } catch (e) { setError(e.message); update(clip.id, 'rendering', false); } }
    return <main className="shell"><header className="topbar"><div className="brand-mark">✦</div><div><p className="eyebrow">LOCAL REELS LAB</p><h1>把長片剪成值得看的片段。</h1></div><span className="status-dot">本機工作區</span></header><section className="hero-grid"><div className="hero-copy"><p className="section-kicker">01 / 上傳素材</p><h2>找到觀眾會停下來看的 15 秒。</h2><p className="hero-description">上傳一支長影片，AI 會先替你找出有價值的片段。你可以修改標題、時間與字卡，再輸出直式 Reels。</p></div><label className="upload-zone"><input type="file" accept="video/mp4,video/quicktime,video/webm,video/x-matroska" onChange={(e) => e.target.files?.[0] && upload(e.target.files[0])} /><span className="upload-icon">↑</span><strong>{selectedFile ? selectedFile.name : '拖曳影片到這裡，或點擊選擇'}</strong><small>MP4 / MOV / WebM / MKV · 最大 2 GB</small>{selectedFile && <span className="file-ready">{status}</span>}{fileId === 'default' && !clips.length && <button type="button" onClick={(e) => { e.preventDefault(); analyze(fileId); }}>開始分析預設影片</button>}</label></section><section className="analysis-settings"><p className="section-kicker">AI 分析參數</p><label>片段數量<input type="number" min="1" max="5" value={clipCount} onChange={(e) => setClipCount(Number(e.target.value))} /></label><label>每段秒數<input type="number" min="10" max="60" value={clipDuration} onChange={(e) => setClipDuration(Number(e.target.value))} /></label><span>AI 會依照設定挑選候選片段，之後仍可逐支微調。</span></section><section className="workspace-preview"><div className="preview-header"><div><p className="section-kicker">02 / 審查與編輯</p><h3>你的片段會在這裡出現</h3></div><span className="muted-label">{status}</span></div>{videoUrl && <video ref={videoRef} className="source-video" src={videoUrl} controls onPlay={stopOtherVideos} onPause={() => setPlayingClipId(null)} />}{error && <p className="error-message">{error}</p>}{clips.length ? <div className="clip-list">{clips.map((clip, i) => <ClipCard key={clip.id} clip={clip} index={i} update={update} updateLayer={updateLayer} setLayer={setLayer} position={position} preview={preview} playing={playingClipId === clip.id} resetPosition={resetPosition} renderOne={renderOne} fonts={fonts} />)}</div> : <div className="empty-track"><div className="track-line" /><span className="track-start">00:00</span><span className="track-end">— — —</span></div>}</section></main>;
}

function ClipCard({ clip, index, update, updateLayer, setLayer, position, preview, playing, resetPosition, renderOne, fonts }) {
  const [open, setOpen] = useState(false);
  const layer = clip.activeLayer || 'topText'; const s = clip.style[layer];
  return <article className={`clip-card ${open ? 'is-open' : 'is-closed'}`}>
    <div className="clip-summary" role="button" tabIndex="0" onClick={() => setOpen(!open)} onKeyDown={(event) => { if (event.key === 'Enter' || event.key === ' ') setOpen(!open); }}><span className="clip-index">0{index + 1}</span><span className="clip-summary-title">{clip.title || '未命名片段'}</span><span className="clip-summary-time">{clip.start_time.toFixed(1)}s – {clip.end_time.toFixed(1)}s</span><button className="summary-preview" type="button" onClick={(event) => { event.stopPropagation(); preview(clip); }}>{playing ? '停止播放' : '預覽片段'}</button><span className="clip-summary-action">{open ? '收合 ↑' : '編輯 ↓'}</span></div>
    {open && <div className="clip-edit-panel"><div className="clip-fields"><label>上欄文字<input value={clip.top_text || clip.title} onChange={(e) => update(clip.id, 'top_text', e.target.value)} /></label><label>下欄文字<input value={clip.caption} onChange={(e) => update(clip.id, 'caption', e.target.value)} /></label><div className="clip-meta"><span>AI 建議時間：{clip.start_time.toFixed(1)}s – {clip.end_time.toFixed(1)}s</span><button type="button" onClick={() => preview(clip)}>{playing ? '停止播放' : '預覽片段'}</button></div><div className="card-editor"><div className="position-stage" onClick={(e) => position(e, clip)}><span className="stage-hint">點擊畫面定位</span><i className="stage-text" style={{ left: `${clip.style.topText.x}%`, top: `${clip.style.topText.y}%`, background: clip.style.topText.color }} /><i className="stage-text" style={{ left: `${clip.style.bottomText.x}%`, top: `${clip.style.bottomText.y}%`, background: clip.style.bottomText.color }} /></div><div className="position-controls"><div className="layer-tabs"><button type="button" className={layer === 'topText' ? 'active' : ''} onClick={() => setLayer(clip.id, 'topText')}>上欄</button><button type="button" className={layer === 'bottomText' ? 'active' : ''} onClick={() => setLayer(clip.id, 'bottomText')}>下欄</button></div><label>字型<select value={s.fontFamily} onChange={(e) => updateLayer(clip.id, layer, 'fontFamily', e.target.value)}>{fonts.map((font) => <option key={font}>{font}</option>)}</select></label><label>顏色<input type="color" value={s.color} onChange={(e) => updateLayer(clip.id, layer, 'color', e.target.value)} /></label><label>字級<input type="number" min="32" max="140" value={s.fontSize} onChange={(e) => updateLayer(clip.id, layer, 'fontSize', e.target.value)} /></label><label>X 軸 <output>{s.x}%</output><input type="range" min="5" max="95" value={s.x} onChange={(e) => updateLayer(clip.id, layer, 'x', e.target.value)} /></label><label>Y 軸 <output>{s.y}%</output><input type="range" min="5" max="95" value={s.y} onChange={(e) => updateLayer(clip.id, layer, 'y', e.target.value)} /></label></div></div><button className="render-one" type="button" onClick={() => renderOne(clip)} disabled={clip.rendering}>{clip.rendering ? '渲染中…' : '渲染這支 Reel'}</button>{clip.renderedUrl && <div className="rendered-result"><video src={clip.renderedUrl} controls onPlay={(event) => document.querySelectorAll('video').forEach((video) => { if (video !== event.currentTarget) video.pause(); })} /><a href={clip.renderedUrl}>下載這支 Reel</a></div>}</div></div>}
  </article>;
}
