import { useEffect, useRef, useState } from 'react';

const API_BASE_URL = (import.meta.env.VITE_API_BASE_URL || '').replace(/\/$/, '');
const fetch = (input, options) => window.fetch(`${API_BASE_URL}${input}`, options);
async function readJson(response) {
  const text = await response.text();
  if (!text.trim()) throw new Error(`後端沒有回應（HTTP ${response.status}）。請確認後端服務已啟動並已連線。`);
  try { return JSON.parse(text); }
  catch { throw new Error(`後端回應格式錯誤（HTTP ${response.status}）。請確認 API 網址設定正確。`); }
}

const makeStyle = () => ({ topText: { color: '#2F80ED', fontSize: 72, fontFamily: 'Noto Sans TC', x: 50, y: 22, width: 88, showFrom: 0, hideAt: 9999 }, bottomText: { color: '#2F80ED', fontSize: 72, fontFamily: 'Noto Sans TC', x: 50, y: 52, width: 88, showFrom: 0, hideAt: 9999 } });
const fonts = [
  { value: 'Noto Sans TC', label: 'Noto Sans TC' },
  { value: 'Iansui', label: '芫荽' },
  { value: 'Hannotate TC', label: '手札體' },
  { value: 'BiauKaiTC', label: '標楷體' },
  { value: 'KouzanBrushFontOTF', label: '衡山毛筆' },
  { value: 'Arial', label: 'Arial' },
  { value: 'Georgia', label: 'Georgia' },
  { value: 'Courier New', label: 'Courier New' },
];

export default function App() {
  const [selectedFile, setSelectedFile] = useState(null), [fileId, setFileId] = useState(null), [clips, setClips] = useState([]), [selectedClipId, setSelectedClipId] = useState(null), [status, setStatus] = useState('等待上傳'), [error, setError] = useState(''), [videoUrl, setVideoUrl] = useState(''), [dimensions, setDimensions] = useState(null), [musicFiles, setMusicFiles] = useState([]), [manualStart, setManualStart] = useState('0'), [manualEnd, setManualEnd] = useState('15'), [clipCount, setClipCount] = useState(3), [clipDuration, setClipDuration] = useState(15), [playingClipId, setPlayingClipId] = useState(null), [previewTime, setPreviewTime] = useState(0), [analyzing, setAnalyzing] = useState(false);
  const videoRef = useRef(null);
  const audioRef = useRef(null);
  const [installPrompt, setInstallPrompt] = useState(null);
  const [installGuide, setInstallGuide] = useState(false);
  const [installVisible, setInstallVisible] = useState(false);

  useEffect(() => {
    const standalone = window.matchMedia('(display-mode: standalone)').matches || window.navigator.standalone === true;
    if (standalone || localStorage.getItem('reel-studio-pwa-installed') === 'true') return undefined;
    const isIos = /iphone|ipad|ipod/i.test(window.navigator.userAgent);
    const dismissedAt = Number(localStorage.getItem('reel-studio-pwa-dismissed-at') || 0);
    const canShowAgain = !dismissedAt || Date.now() - dismissedAt > 1000 * 60 * 60 * 24 * 30;
    const onBeforeInstallPrompt = (event) => { event.preventDefault(); setInstallPrompt(event); if (canShowAgain) setInstallVisible(true); };
    const onInstalled = () => { localStorage.setItem('reel-studio-pwa-installed', 'true'); setInstallVisible(false); setInstallPrompt(null); };
    window.addEventListener('beforeinstallprompt', onBeforeInstallPrompt);
    window.addEventListener('appinstalled', onInstalled);
    if (isIos && canShowAgain) { setInstallGuide(true); setInstallVisible(true); }
    return () => { window.removeEventListener('beforeinstallprompt', onBeforeInstallPrompt); window.removeEventListener('appinstalled', onInstalled); };
  }, []);

  const dismissInstall = () => { localStorage.setItem('reel-studio-pwa-dismissed-at', String(Date.now())); setInstallVisible(false); };
  const installApp = async () => { if (!installPrompt) return; installPrompt.prompt(); await installPrompt.userChoice; setInstallPrompt(null); setInstallVisible(false); };

  useEffect(() => { fetch('/api/default-video').then((r) => r.ok ? r.json() : null).then((v) => { if (v) { setFileId(v.fileId); setVideoUrl(v.videoUrl); setDimensions(v.dimensions); setSelectedFile({ name: v.originalName }); setStatus('預設影片已載入，可直接開始分析'); } }).catch(() => {}); }, []);
  useEffect(() => { fetch('/api/music').then((r) => r.ok ? r.json() : null).then((v) => v && setMusicFiles(v.music || [])).catch(() => {}); }, []);
  const analyze = async (id) => { setError(''); setAnalyzing(true); setStatus('正在分析語音與高光片段…'); try { const r = await fetch('/api/analyze', { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ fileId: id, clipCount, clipDuration }) }); const data = await readJson(r); if (!r.ok) throw new Error(data.error || '影片分析失敗'); const next = data.clips.map((c) => ({ ...c, top_text: c.top_text || c.title, caption: c.bottom_text || c.title, aiStart: c.start_time, aiEnd: c.end_time, outputAspect: 'original', style: makeStyle(), activeLayer: 'topText', musicFile: '', musicVolume: 0.35, keepOriginalAudio: true })); setClips(next); setSelectedClipId(next[0]?.id || null); setStatus('已找到 ' + data.clips.length + ' 個候選片段'); } catch (e) { setError(e.message); setStatus('需要處理'); } finally { setAnalyzing(false); } };
  async function upload(file) { setSelectedFile(file); setVideoUrl(URL.createObjectURL(file)); setClips([]); setSelectedClipId(null); setStatus('正在上傳…'); try { const form = new FormData(); form.append('video', file); const r = await fetch('/api/upload', { method: 'POST', body: form }); const data = await readJson(r); if (!r.ok) throw new Error(data.error); setFileId(data.fileId); setDimensions(data.dimensions); await analyze(data.fileId); } catch (e) { setError(e.message); setStatus('需要處理'); } }
  const update = (id, field, value) => setClips((all) => all.map((c) => c.id === id ? { ...c, [field]: ['start_time', 'end_time'].includes(field) ? Number(value) : value, ...(['renderedUrl', 'downloadUrl', 'rendering'].includes(field) ? {} : { renderedUrl: undefined, downloadUrl: undefined }) } : c));
  const updateLayer = (id, layer, field, value) => setClips((all) => all.map((c) => c.id === id ? { ...c, renderedUrl: undefined, style: { ...c.style, [layer]: { ...c.style[layer], [field]: ['x', 'y', 'fontSize', 'width', 'showFrom', 'hideAt'].includes(field) ? (value === '' ? '' : Number(value)) : value } } } : c));
  const setLayer = (id, activeLayer) => setClips((all) => all.map((c) => c.id === id ? { ...c, activeLayer } : c));
  const resetPosition = (id, layer) => { updateLayer(id, layer, 'x', 50); updateLayer(id, layer, 'y', layer === 'topText' ? 22 : 52); };
  const updateAspect = (id, value) => setClips((all) => all.map((c) => c.id === id ? { ...c, outputAspect: value, renderedUrl: undefined } : c));
  const addManualClip = () => { const start = Number(manualStart); const end = Number(manualEnd); if (!Number.isFinite(start) || !Number.isFinite(end) || start < 0 || end <= start) { setError('手動片段時間無效，請確認開始與結束時間。'); return; } const clip = { id: `manual-${Date.now()}`, source: 'manual', title: `手動片段${clips.filter((item) => item.source === 'manual').length ? clips.filter((item) => item.source === 'manual').length + 1 : ''}`, top_text: '', caption: '', start_time: start, end_time: end, aiStart: start, aiEnd: end, outputAspect: 'original', style: makeStyle(), activeLayer: 'topText', musicFile: '', musicVolume: 0.35, keepOriginalAudio: true }; setClips((all) => [...all, clip]); setSelectedClipId(clip.id); setError(''); };
  const aspectLabel = (aspect) => aspect === '1:1' ? '1:1 正方形' : aspect === 'original' ? '原始比例' : '9:16 Reels';
  const stopOtherVideos = (event) => { document.querySelectorAll('video').forEach((video) => { if (video !== event.currentTarget) video.pause(); }); };
  const preview = (clip) => { const v = videoRef.current; const a = audioRef.current; if (!v) return; if (playingClipId === clip.id && !v.paused) { v.pause(); a?.pause(); v.muted = false; v.ontimeupdate = null; setPlayingClipId(null); return; } document.querySelectorAll('video').forEach((video) => video.pause()); a?.pause(); v.ontimeupdate = null; v.muted = Boolean(clip.musicFile && clip.keepOriginalAudio === false); v.currentTime = clip.start_time; if (a && clip.musicFile) { a.src = `${API_BASE_URL}/api/music/${encodeURIComponent(clip.musicFile)}`; a.currentTime = 0; a.volume = Number(clip.musicVolume ?? 0.35); a.play().catch(() => {}); } setPreviewTime(0); v.play(); setPlayingClipId(clip.id); v.ontimeupdate = () => { setPreviewTime(Math.max(0, v.currentTime - clip.start_time)); if (v.currentTime >= clip.end_time) { v.pause(); a?.pause(); v.muted = false; v.ontimeupdate = null; setPlayingClipId(null); } }; };
  async function renderOne(clip) { if (!Number.isFinite(clip.start_time) || !Number.isFinite(clip.end_time) || clip.end_time <= clip.start_time) { setError('結束時間必須大於開始時間，請先調整片段範圍。'); return; } update(clip.id, 'rendering', true); try { const r = await fetch('/api/render', { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ fileId, clips: [clip] }) }); const data = await readJson(r); if (!r.ok) throw new Error(data.error || '影片渲染失敗'); update(clip.id, 'renderedUrl', data.outputs[0].previewUrl); update(clip.id, 'downloadUrl', data.outputs[0].downloadUrl); update(clip.id, 'rendering', false); setStatus('片段 ' + (clips.findIndex((c) => c.id === clip.id) + 1) + ' 已完成渲染'); } catch (e) { setError(e.message); update(clip.id, 'rendering', false); } }

  const selectedClip = clips.find((clip) => clip.id === selectedClipId) || clips[0];
  return <main className="shell">
    {installVisible && <InstallPrompt ios={installGuide} onInstall={installApp} onDismiss={dismissInstall} />}
    <audio ref={audioRef} preload="metadata" className="music-preview-audio" />
    <header className="studio-header"><div><p className="eyebrow">REEL STUDIO</p><h1>{selectedFile?.name || '尚未選擇影片'}</h1></div><span className="save-state">● {status}</span></header>
    <section className="hero-grid"><div className="hero-copy"><p className="section-kicker">01 / 上傳素材</p><h2>找到觀眾會停下來看的 15 秒。</h2><p className="hero-description">上傳一支長影片，AI 會先替你找出有價值的片段。</p></div><div className="upload-zone"><label className="upload-select"><input type="file" accept="video/mp4,video/quicktime,video/webm,video/x-matroska" onChange={(e) => e.target.files?.[0] && upload(e.target.files[0])} /><span className="upload-icon">↑</span><strong>{selectedFile ? selectedFile.name : '選擇長影片'}</strong><small>MP4 / MOV / WebM / MKV · 最大 2 GB</small></label>{fileId === 'default' && !clips.length && <button className={analyzing ? 'is-loading' : ''} type="button" disabled={analyzing} onClick={() => analyze(fileId)}>{analyzing ? 'AI 分析中…' : '開始分析預設影片'}</button>}<section className="analysis-settings"><p className="section-kicker">AI 分析參數</p><div className="analysis-fields"><label>片段數量<input type="number" min="1" max="5" value={clipCount} onChange={(e) => setClipCount(Number(e.target.value))} /></label><label>每段秒數<input type="number" min="10" max="60" value={clipDuration} onChange={(e) => setClipDuration(Number(e.target.value))} /></label></div><span>AI 會依照設定找出候選片段，之後仍可逐支微調。</span></section></div></section>
    {error && <p className="error-message">{error}</p>}
    {fileId && <div className="manual-clip-form"><span>手動新增片段</span><label>開始<input type="number" min="0" step="0.1" value={manualStart} onChange={(e) => setManualStart(e.target.value)} /></label><label>結束<input type="number" min="0" step="0.1" value={manualEnd} onChange={(e) => setManualEnd(e.target.value)} /></label><button type="button" className="manual-clip-button" onClick={addManualClip}>新增片段</button></div>}
    <section className="studio-workbench">
      <aside className="clip-sidebar"><div className="panel-heading"><div><p className="section-kicker">02 / 片段</p><h3>候選片段</h3></div><span>{clips.length} 個</span></div>{clips.length ? clips.map((clip, index) => <button type="button" className={'clip-item ' + (selectedClip?.id === clip.id ? 'is-selected' : '')} key={clip.id} onClick={() => { setSelectedClipId(clip.id); setPlayingClipId(null); }}><span className="clip-item-index">0{index + 1}</span><span className="clip-item-copy"><strong>{clip.title || '未命名片段'}</strong><small>目前 {clip.start_time.toFixed(1)}s – {clip.end_time.toFixed(1)}s</small><em>AI 建議 {clip.aiStart.toFixed(1)}s – {clip.aiEnd.toFixed(1)}s</em></span><span className="clip-item-play" onClick={(event) => { event.stopPropagation(); setSelectedClipId(clip.id); preview(clip); }}>{playingClipId === clip.id ? '■' : '▶'}</span></button>) : <div className="sidebar-empty">完成分析後，片段會出現在這裡。</div>}</aside>
      <section className="preview-panel"><div className="panel-heading"><div><p className="section-kicker">03 / 預覽</p><h3>{selectedClip?.title || '預覽與調整'}</h3></div>{selectedClip && <span className="preview-range">{aspectLabel(selectedClip.outputAspect)}</span>}</div>{videoUrl ? <video ref={videoRef} className={'source-video workbench-video ' + (selectedClip?.outputAspect === '1:1' ? 'is-square' : selectedClip?.outputAspect === 'original' ? 'is-original' : 'is-vertical')} style={{ aspectRatio: selectedClip?.outputAspect === '1:1' ? '1 / 1' : selectedClip?.outputAspect === 'original' && dimensions ? dimensions.width + ' / ' + dimensions.height : '9 / 16' }} src={videoUrl} controls onPlay={stopOtherVideos} onPause={() => setPlayingClipId(null)} onTimeUpdate={() => { if (selectedClip && videoRef.current) setPreviewTime(Math.max(0, videoRef.current.currentTime - selectedClip.start_time)); }} /> : <div className="preview-empty">先上傳影片</div>}{selectedClip && <div className="preview-caption"><span className={previewTime >= Number(selectedClip.style.topText.showFrom || 0) && previewTime <= Number(selectedClip.style.topText.hideAt >= 9999 ? selectedClip.end_time - selectedClip.start_time : selectedClip.style.topText.hideAt) ? '' : 'is-hidden'} style={{ left: selectedClip.style.topText.x + '%', top: selectedClip.style.topText.y + '%', maxWidth: selectedClip.style.topText.width + '%', fontSize: Math.max(8, selectedClip.style.topText.fontSize * (selectedClip.outputAspect === '1:1' ? 560 : 315) / 1080) + 'px', fontFamily: selectedClip.style.topText.fontFamily, color: selectedClip.style.topText.color }}>{selectedClip.top_text}</span><span className={previewTime >= Number(selectedClip.style.bottomText.showFrom || 0) && previewTime <= Number(selectedClip.style.bottomText.hideAt >= 9999 ? selectedClip.end_time - selectedClip.start_time : selectedClip.style.bottomText.hideAt) ? '' : 'is-hidden'} style={{ left: selectedClip.style.bottomText.x + '%', top: selectedClip.style.bottomText.y + '%', maxWidth: selectedClip.style.bottomText.width + '%', fontSize: Math.max(8, selectedClip.style.bottomText.fontSize * (selectedClip.outputAspect === '1:1' ? 560 : 315) / 1080) + 'px', fontFamily: selectedClip.style.bottomText.fontFamily, color: selectedClip.style.bottomText.color }}>{selectedClip.caption}</span></div>}{selectedClip && <div className="timeline-summary"><span>目前輸出 {selectedClip.start_time.toFixed(1)}s – {selectedClip.end_time.toFixed(1)}s</span><span>片段長度 {Math.max(0, selectedClip.end_time - selectedClip.start_time).toFixed(1)} 秒</span></div>}</section>
      {selectedClip && <ClipControls clip={selectedClip} update={update} updateLayer={updateLayer} resetPosition={resetPosition} renderOne={renderOne} />}
      {selectedClip ? <ClipSettings clip={selectedClip} dimensions={dimensions} musicFiles={musicFiles} update={update} updateLayer={updateLayer} updateAspect={updateAspect} setLayer={setLayer} resetPosition={resetPosition} renderOne={renderOne} fonts={fonts} playing={playingClipId === selectedClip.id} preview={preview} /> : <aside className="settings-panel settings-empty">選擇一個片段開始編輯。</aside>}
    </section>
  </main>;
}

function InstallPrompt({ ios, onInstall, onDismiss }) {
  return <aside className="pwa-install-prompt" aria-label="安裝 Reel Studio">
    <div className="pwa-install-icon" aria-hidden="true">▶</div>
    <div className="pwa-install-copy"><strong>把 Reel Studio 放到主畫面</strong><p>{ios ? '點選瀏覽器的分享，再選「加入主畫面」。' : '安裝後可像 App 一樣快速開啟。'}</p></div>
    {ios ? <button type="button" className="pwa-install-action" onClick={onDismiss}>知道了</button> : <button type="button" className="pwa-install-action" onClick={onInstall}>安裝 App</button>}
    <button type="button" className="pwa-install-close" aria-label="關閉安裝提示" onClick={onDismiss}>×</button>
  </aside>;
}

function ClipControls({ clip, update, updateLayer, resetPosition, renderOne }) {
  const layer = clip.activeLayer || 'topText';
  const s = clip.style[layer];
  return <section className="preview-controls"><div className="controls-heading"><div><p className="section-kicker">05 / 調整與輸出</p><h3>位置與渲染</h3></div><span>{layer === 'topText' ? '上欄文字' : '下欄文字'}</span></div><div className="position-group"><div className="control-group-title">位置 <button type="button" onClick={() => resetPosition(clip.id, layer)}>重設位置</button></div><label>X 軸 <output>{s.x}%</output><input type="range" min="5" max="95" value={s.x} onChange={(e) => updateLayer(clip.id, layer, 'x', e.target.value)} /></label><label>Y 軸 <output>{s.y}%</output><input type="range" min="5" max="95" value={s.y} onChange={(e) => updateLayer(clip.id, layer, 'y', e.target.value)} /></label></div><div className="time-editor"><span className="setting-label">片段時間</span><div><label>開始<input type="number" min="0" step="0.1" value={clip.start_time} onChange={(e) => update(clip.id, 'start_time', e.target.value)} /></label><label>結束<input type="number" min="0" step="0.1" value={clip.end_time} onChange={(e) => update(clip.id, 'end_time', e.target.value)} /></label></div><small>AI 建議 {clip.aiStart.toFixed(1)}s – {clip.aiEnd.toFixed(1)}s</small></div><div className="settings-actions"><button type="button" className="render-one" onClick={() => renderOne(clip)} disabled={clip.rendering}>{clip.rendering ? '渲染中…' : '渲染此片段 ↗'}</button></div>{clip.renderedUrl && <div className="rendered-result"><video src={clip.renderedUrl} controls preload="metadata" onPlay={(event) => document.querySelectorAll('video').forEach((video) => { if (video !== event.currentTarget) video.pause(); })} /><a href={clip.downloadUrl || clip.renderedUrl}>下載此片段 ↓</a></div>}</section>;
}
function ClipSettings({ clip, dimensions, musicFiles, update, updateLayer, updateAspect, setLayer, resetPosition, renderOne, fonts, playing, preview }) {
  const layer = clip.activeLayer || 'topText';
  const s = clip.style[layer];
  const clipLength = Math.max(0, Number(clip.end_time) - Number(clip.start_time));
  const showFrom = Math.min(clipLength, Math.max(0, Number(s.showFrom || 0)));
  const hideAt = Math.min(clipLength, Math.max(showFrom, Number(s.hideAt >= 9999 ? clipLength : s.hideAt)));
  return <aside className="settings-panel">
    <div className="panel-heading"><div><p className="section-kicker">04 / 字卡設定</p><h3>編輯字卡</h3></div><span className="editing-label">正在編輯：{layer === 'topText' ? '上欄文字' : '下欄文字'}</span></div>
    <label className="setting-field">片段主題名稱<input value={clip.title || ''} onChange={(e) => update(clip.id, 'title', e.target.value)} /></label>
    <label className="setting-field">輸出比例<select value={clip.outputAspect || 'original'} onChange={(e) => updateAspect(clip.id, e.target.value)}><option value="original">原始比例{dimensions ? `（${dimensions.width} × ${dimensions.height}）` : ''}</option><option value="9:16">9:16 Reels（1080 × 1920）</option><option value="1:1">1:1 正方形（1080 × 1080）</option></select></label>
    <label className="setting-field music-field">背景音樂<select value={clip.musicFile || ''} onChange={(e) => update(clip.id, 'musicFile', e.target.value)}><option value="">不使用背景音樂</option>{musicFiles.map((file) => <option key={file} value={file}>{file}</option>)}</select></label>
    {clip.musicFile && <div className="music-controls settings-music-controls"><label>音樂音量 <output>{Math.round(Number(clip.musicVolume ?? 0.35) * 100)}%</output><input type="range" min="0" max="1" step="0.05" value={clip.musicVolume ?? 0.35} onChange={(e) => update(clip.id, 'musicVolume', Number(e.target.value))} /></label><label className="checkbox-field"><input type="checkbox" checked={clip.keepOriginalAudio !== false} onChange={(e) => update(clip.id, 'keepOriginalAudio', e.target.checked)} /> 保留原影片聲音</label><button type="button" className="music-preview-button" onClick={() => preview(clip)}>{playing ? '暫停試聽' : '試聽此片段'}</button><small>播放片段時同步試聽；渲染時會套用相同設定。</small></div>}
    <div className="layer-tabs"><button type="button" className={layer === 'topText' ? 'active' : ''} onClick={() => setLayer(clip.id, 'topText')}>上欄</button><button type="button" className={layer === 'bottomText' ? 'active' : ''} onClick={() => setLayer(clip.id, 'bottomText')}>下欄</button></div>
    <label className="setting-field">文字內容<input value={layer === 'topText' ? clip.top_text : clip.caption} onChange={(e) => update(clip.id, layer === 'topText' ? 'top_text' : 'caption', e.target.value)} /></label>
    <div className="caption-timing"><span className="setting-label">文字出現時間（{layer === 'topText' ? '上欄' : '下欄'}）</span><div><label>出現<input type="number" min="0" max={clipLength} step="0.1" value={s.showFrom === '' ? '' : showFrom} onChange={(e) => updateLayer(clip.id, layer, 'showFrom', e.target.value === '' ? '' : e.target.value)} /></label><label>消失<input type="number" min="0" max={clipLength} step="0.1" value={s.hideAt === '' ? '' : hideAt} onChange={(e) => updateLayer(clip.id, layer, 'hideAt', e.target.value === '' ? '' : e.target.value)} /></label></div><small>以片段開始處為 0 秒，最長 {clipLength.toFixed(1)} 秒</small></div>
    <div className="time-editor"><span className="setting-label">片段時間</span><div><label>開始<input type="number" min="0" step="0.1" value={clip.start_time} onChange={(e) => update(clip.id, 'start_time', e.target.value)} /></label><label>結束<input type="number" min="0" step="0.1" value={clip.end_time} onChange={(e) => update(clip.id, 'end_time', e.target.value)} /></label></div><small>AI 建議 {clip.aiStart.toFixed(1)}s – {clip.aiEnd.toFixed(1)}s</small></div>
    <div className="style-grid"><label className="setting-field">字型<select value={s.fontFamily} onChange={(e) => updateLayer(clip.id, layer, 'fontFamily', e.target.value)}>{fonts.map((font) => <option key={font.value} value={font.value}>{font.label}</option>)}</select></label><label className="setting-field">字級<div className="number-field"><input type="number" min="16" max="240" value={s.fontSize} onChange={(e) => updateLayer(clip.id, layer, 'fontSize', e.target.value)} /></div></label><label className="setting-field color-setting">顏色<div className="color-field"><input type="color" value={s.color} onChange={(e) => updateLayer(clip.id, layer, 'color', e.target.value)} /></div></label></div>
    <div className="position-group"><div className="control-group-title">位置 <button type="button" onClick={() => resetPosition(clip.id, layer)}>重設位置</button></div><label>X 軸 <output>{s.x}%</output><input type="range" min="5" max="95" value={s.x} onChange={(e) => updateLayer(clip.id, layer, 'x', e.target.value)} /></label><label>Y 軸 <output>{s.y}%</output><input type="range" min="5" max="95" value={s.y} onChange={(e) => updateLayer(clip.id, layer, 'y', e.target.value)} /></label></div>
    <div className="settings-actions"><button type="button" className="render-one" onClick={() => renderOne(clip)} disabled={clip.rendering}>{clip.rendering ? '渲染中…' : '渲染此片段 ↗'}</button></div>{clip.renderedUrl && <div className="rendered-result"><video src={clip.renderedUrl} controls preload="metadata" onPlay={(event) => document.querySelectorAll('video').forEach((video) => { if (video !== event.currentTarget) video.pause(); })} /><a href={clip.downloadUrl || clip.renderedUrl}>下載此片段 ↓</a></div>}
  </aside>;
}
